language: ruby

rvm:
  - 1.9.3-p547

before_install:
  - git submodule update --init --recursive

before_script:
  - bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)
  - source /home/travis/.gvm/scripts/gvm
  - gvm install go1.3
  - gvm use go1.3

script: bin/test

env:
  global:
    secure: "HhB9Uz44WH7hmq4Fmu+bnIxtX7h5f9DVdJj3xNJpUTiOITnektwLRF4+Djf3+MaXTswQ+/xtBqy40gdraKHARuhWV3a3EVCSPP8H5OUUoGPmnUCbl/DOY88/Gl2GysJfEmiZ34a8CYRatjIZs9cyJXDQvqhEPA5xmdTWS5hzM14="
