# See src/lib/dea/config.rb for optional config values.

# Base directory for dea, application directories, dea temp files, etc. are all relative to this.
base_dir: C:/IronFoundry/dea_ng

logging:
  level: all
  file: C:/IronFoundry/log/dea_ng.log

loggregator:
  # UPDATE: Cloud Controller IP
  router: 127.0.0.1:3456
  shared_secret: loggregatorsharedsecret
  
resources:
  memory_mb: 2048
  memory_overcommit_factor: 2
  disk_mb: 2048
  disk_overcommit_factor: 2

nats_servers:
  # UPDATE: Username, password and Cloud Controller IP
  - nats://nats:nats@127.0.0.1:4222/

pid_filename: C:/IronFoundry/run/dea_ng.pid

warden_socket: tcp://localhost:4444

evacuation_bail_out_time_in_seconds: 900

default_health_check_timeout: 60 # 1 minute

index: 0
# UPDATE: Cloud Controller IP / Hostname
domain: "127.0.0.1.xip.io"

staging:
  enabled: true
  environment:
    # UPDATE: Ruby bin path
    PATH: C:\Ruby193\bin # NB: backslashes
    BUILDPACK_CACHE: C:/IronFoundry/buildpack_cache
  memory_limit_mb: 1024
  disk_limit_mb: 2048
  cpu_limit_shares: 512
  max_staging_duration: 900 # 15 minutes

instance:
  cpu_limit_shares: 256

# UPDATE: Ruby bin path
dea_ruby: C:/Ruby193/bin/ruby.exe

# For Go-based directory server
directory_server:
  protocol: 'http'
  v1_port: 4385
  v2_port: 5678
  file_api_port: 1234
  streaming_timeout: 10
  logging:
    file: C:/IronFoundry/log/directory_server.log
    level: all

stacks:
  - mswin-clr

# Hook scripts for droplet start/stop
# hooks:
#   before_start: path/to/script
#   after_start: path/to/script
#   before_stop: path/to/script
#   after_stop: path/to/script

placement_properties:
  zone: "default"